<?php
/**
 * PoaDocumentSubChecks
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Irisnet\API\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Irisnet API
 *
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Irisnet\API\Client\Model;

use \ArrayAccess;
use \Irisnet\API\Client\ObjectSerializer;

/**
 * PoaDocumentSubChecks Class Doc Comment
 *
 * @category Class
 * @description Contains information on poaDocument sub-checks
 * @package  Irisnet\API\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PoaDocumentSubChecks implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PoaDocumentSubChecks';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'firstName' => 'string',
        'lastName' => 'string',
        'documentAge' => 'string',
        'ipOriginatesInAddressCountry' => 'string',
        'ipNearbyAddress' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'firstName' => null,
        'lastName' => null,
        'documentAge' => null,
        'ipOriginatesInAddressCountry' => null,
        'ipNearbyAddress' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'firstName' => false,
        'lastName' => false,
        'documentAge' => false,
        'ipOriginatesInAddressCountry' => false,
        'ipNearbyAddress' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'firstName' => 'firstName',
        'lastName' => 'lastName',
        'documentAge' => 'documentAge',
        'ipOriginatesInAddressCountry' => 'ipOriginatesInAddressCountry',
        'ipNearbyAddress' => 'ipNearbyAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'firstName' => 'setFirstName',
        'lastName' => 'setLastName',
        'documentAge' => 'setDocumentAge',
        'ipOriginatesInAddressCountry' => 'setIpOriginatesInAddressCountry',
        'ipNearbyAddress' => 'setIpNearbyAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'firstName' => 'getFirstName',
        'lastName' => 'getLastName',
        'documentAge' => 'getDocumentAge',
        'ipOriginatesInAddressCountry' => 'getIpOriginatesInAddressCountry',
        'ipNearbyAddress' => 'getIpNearbyAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FIRST_NAME_PASSED = 'passed';
    public const FIRST_NAME_FAILED = 'failed';
    public const FIRST_NAME_NOT_PROCESSED = 'not_processed';
    public const LAST_NAME_PASSED = 'passed';
    public const LAST_NAME_FAILED = 'failed';
    public const LAST_NAME_NOT_PROCESSED = 'not_processed';
    public const DOCUMENT_AGE_PASSED = 'passed';
    public const DOCUMENT_AGE_FAILED = 'failed';
    public const DOCUMENT_AGE_NOT_PROCESSED = 'not_processed';
    public const IP_ORIGINATES_IN_ADDRESS_COUNTRY_PASSED = 'passed';
    public const IP_ORIGINATES_IN_ADDRESS_COUNTRY_FAILED = 'failed';
    public const IP_ORIGINATES_IN_ADDRESS_COUNTRY_NOT_PROCESSED = 'not_processed';
    public const IP_NEARBY_ADDRESS_PASSED = 'passed';
    public const IP_NEARBY_ADDRESS_FAILED = 'failed';
    public const IP_NEARBY_ADDRESS_NOT_PROCESSED = 'not_processed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFirstNameAllowableValues()
    {
        return [
            self::FIRST_NAME_PASSED,
            self::FIRST_NAME_FAILED,
            self::FIRST_NAME_NOT_PROCESSED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLastNameAllowableValues()
    {
        return [
            self::LAST_NAME_PASSED,
            self::LAST_NAME_FAILED,
            self::LAST_NAME_NOT_PROCESSED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDocumentAgeAllowableValues()
    {
        return [
            self::DOCUMENT_AGE_PASSED,
            self::DOCUMENT_AGE_FAILED,
            self::DOCUMENT_AGE_NOT_PROCESSED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIpOriginatesInAddressCountryAllowableValues()
    {
        return [
            self::IP_ORIGINATES_IN_ADDRESS_COUNTRY_PASSED,
            self::IP_ORIGINATES_IN_ADDRESS_COUNTRY_FAILED,
            self::IP_ORIGINATES_IN_ADDRESS_COUNTRY_NOT_PROCESSED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIpNearbyAddressAllowableValues()
    {
        return [
            self::IP_NEARBY_ADDRESS_PASSED,
            self::IP_NEARBY_ADDRESS_FAILED,
            self::IP_NEARBY_ADDRESS_NOT_PROCESSED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('firstName', $data ?? [], null);
        $this->setIfExists('lastName', $data ?? [], null);
        $this->setIfExists('documentAge', $data ?? [], null);
        $this->setIfExists('ipOriginatesInAddressCountry', $data ?? [], null);
        $this->setIfExists('ipNearbyAddress', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFirstNameAllowableValues();
        if (!is_null($this->container['firstName']) && !in_array($this->container['firstName'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'firstName', must be one of '%s'",
                $this->container['firstName'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLastNameAllowableValues();
        if (!is_null($this->container['lastName']) && !in_array($this->container['lastName'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'lastName', must be one of '%s'",
                $this->container['lastName'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDocumentAgeAllowableValues();
        if (!is_null($this->container['documentAge']) && !in_array($this->container['documentAge'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'documentAge', must be one of '%s'",
                $this->container['documentAge'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getIpOriginatesInAddressCountryAllowableValues();
        if (!is_null($this->container['ipOriginatesInAddressCountry']) && !in_array($this->container['ipOriginatesInAddressCountry'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'ipOriginatesInAddressCountry', must be one of '%s'",
                $this->container['ipOriginatesInAddressCountry'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getIpNearbyAddressAllowableValues();
        if (!is_null($this->container['ipNearbyAddress']) && !in_array($this->container['ipNearbyAddress'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'ipNearbyAddress', must be one of '%s'",
                $this->container['ipNearbyAddress'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets firstName
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string|null $firstName Indicates whether the first name is valid
     *
     * @return self
     */
    public function setFirstName($firstName)
    {
        if (is_null($firstName)) {
            throw new \InvalidArgumentException('non-nullable firstName cannot be null');
        }
        $allowedValues = $this->getFirstNameAllowableValues();
        if (!in_array($firstName, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'firstName', must be one of '%s'",
                    $firstName,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string|null $lastName Indicates whether the last name is valid
     *
     * @return self
     */
    public function setLastName($lastName)
    {
        if (is_null($lastName)) {
            throw new \InvalidArgumentException('non-nullable lastName cannot be null');
        }
        $allowedValues = $this->getLastNameAllowableValues();
        if (!in_array($lastName, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'lastName', must be one of '%s'",
                    $lastName,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets documentAge
     *
     * @return string|null
     */
    public function getDocumentAge()
    {
        return $this->container['documentAge'];
    }

    /**
     * Sets documentAge
     *
     * @param string|null $documentAge Indicates whether the age of the document is valid (not older than 3 months)
     *
     * @return self
     */
    public function setDocumentAge($documentAge)
    {
        if (is_null($documentAge)) {
            throw new \InvalidArgumentException('non-nullable documentAge cannot be null');
        }
        $allowedValues = $this->getDocumentAgeAllowableValues();
        if (!in_array($documentAge, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'documentAge', must be one of '%s'",
                    $documentAge,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['documentAge'] = $documentAge;

        return $this;
    }

    /**
     * Gets ipOriginatesInAddressCountry
     *
     * @return string|null
     */
    public function getIpOriginatesInAddressCountry()
    {
        return $this->container['ipOriginatesInAddressCountry'];
    }

    /**
     * Sets ipOriginatesInAddressCountry
     *
     * @param string|null $ipOriginatesInAddressCountry Indicates whether the client IP originates in the country of the address
     *
     * @return self
     */
    public function setIpOriginatesInAddressCountry($ipOriginatesInAddressCountry)
    {
        if (is_null($ipOriginatesInAddressCountry)) {
            throw new \InvalidArgumentException('non-nullable ipOriginatesInAddressCountry cannot be null');
        }
        $allowedValues = $this->getIpOriginatesInAddressCountryAllowableValues();
        if (!in_array($ipOriginatesInAddressCountry, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'ipOriginatesInAddressCountry', must be one of '%s'",
                    $ipOriginatesInAddressCountry,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ipOriginatesInAddressCountry'] = $ipOriginatesInAddressCountry;

        return $this;
    }

    /**
     * Gets ipNearbyAddress
     *
     * @return string|null
     */
    public function getIpNearbyAddress()
    {
        return $this->container['ipNearbyAddress'];
    }

    /**
     * Sets ipNearbyAddress
     *
     * @param string|null $ipNearbyAddress Indicates whether the client IP is in reasonable distance from the address
     *
     * @return self
     */
    public function setIpNearbyAddress($ipNearbyAddress)
    {
        if (is_null($ipNearbyAddress)) {
            throw new \InvalidArgumentException('non-nullable ipNearbyAddress cannot be null');
        }
        $allowedValues = $this->getIpNearbyAddressAllowableValues();
        if (!in_array($ipNearbyAddress, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'ipNearbyAddress', must be one of '%s'",
                    $ipNearbyAddress,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ipNearbyAddress'] = $ipNearbyAddress;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


